all:
  children:

    target_vms:
      children:
        ubuntu:
          hosts:
            ubuntu:
              ansible_host: 192.168.1.227
              ansible_user: ubuntu
              ansible_python_interpreter: /usr/bin/python3
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
