openapi: 3.0.0
info:
  title: GigHive Upload API
  version: 1.0.0
paths:
  /upload:
    post:
      summary: Upload a media file (audio or video)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                title:
                  type: string
              required:
                - file
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
        '400':
          description: Validation error

