---
# roles/docker/tasks/overlay_gighive.yml

- name: Ensure web_root exists
  ansible.builtin.file:
    path: "{{ web_root }}"
    state: directory
    mode: '0755'
  tags:
    - docker

- name: Deploy GigHive HTML to web_root
  ansible.builtin.synchronize:
    mode: push
    src: "{{ role_path }}/files/apache/html/"
    dest: "{{ web_root }}/"
    recursive: yes
    delete: yes
  tags:
    - docker

- name: Remove old BlueGreen overrides when disabled
  ansible.builtin.file:
    path: "{{ web_root }}/blue_green"
    state: absent
  when: not (blue_green | default(false) | bool)
  tags:
    - blue_green

- name: Stage BlueGreen GUI overrides into web_root when enabled
  become: false
  ansible.builtin.synchronize:
    mode: push
    src: "{{ role_path }}/files/apache/blue_green/"
    dest: "{{ web_root }}/"
    recursive: yes
    delete: no
  when: (blue_green | default(false) | bool)
  tags:
    - blue_green 
  delegate_to: localhost

